# Generated by Django 5.2.5 on 2025-08-18 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adimage_review_searchquery_ad_area_ad_is_demo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='searchquery',
            name='ads_searchq_ts_e780ff_idx',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='ts',
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='q',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['ad', 'tenant'], name='ads_review_ad_id_1232b4_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['ad', 'rating'], name='ads_review_ad_id_5ed924_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['created_at'], name='ads_searchq_created_baa43a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['q'], name='ads_searchq_q_314beb_idx'),
        ),
        migrations.AddField(
            model_name='adview',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_modules', to='ads.ad'),
        ),
        migrations.AddField(
            model_name='adview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['ad', 'created_at'], name='ads_adview_ad_id_656625_idx'),
        ),
    ]
