# Generated by Django 5.2.5 on 2025-08-18 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_adview_alter_searchquery_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['ad', 'user', 'created_at'], name='idx_adview_ad_user_created'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['ad', 'ip', 'created_at'], name='idx_adview_ad_ip_created'),
        ),
    ]
