# Generated by Django 5.2.5 on 2025-08-19 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_adview_idx_adview_ad_user_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ad',
            name='ads_ad_price_b613fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='ad',
            name='ads_ad_rooms_5643af_idx',
        ),
        migrations.RemoveIndex(
            model_name='ad',
            name='ads_ad_area_24c30d_idx',
        ),
        migrations.RemoveIndex(
            model_name='adview',
            name='ads_adview_ad_id_656625_idx',
        ),
        migrations.RenameIndex(
            model_name='adview',
            new_name='adview_user_dedup_idx',
            old_name='idx_adview_ad_user_created',
        ),
        migrations.RenameIndex(
            model_name='adview',
            new_name='adview_ip_dedup_idx',
            old_name='idx_adview_ad_ip_created',
        ),
        migrations.RenameIndex(
            model_name='searchquery',
            new_name='searchquery_q_idx',
            old_name='ads_searchq_q_314beb_idx',
        ),
        migrations.RenameIndex(
            model_name='searchquery',
            new_name='searchquery_created_idx',
            old_name='ads_searchq_created_baa43a_idx',
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['is_active', 'created_at'], name='ad_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['latitude', 'longitude'], name='ad_lat_lon_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['housing_type'], name='ad_housing_type_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['ad', 'status', 'date_from', 'date_to'], name='booking_overlap_idx'),
        ),
    ]
