# Generated by Django 5.2.5 on 2025-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_review_unique_together_review_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='housing_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('loft', 'Loft'), ('room', 'Room'), ('townhouse', 'Townhouse'), ('villa', 'Villa')], default='apartment', max_length=20),
        ),
    ]
