# Generated by Django 5.2.5 on 2025-08-27 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ad_housing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adview',
            name='anon_ip_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['ad', 'anon_ip_hash', 'created_at'], name='adview_anonhash_dedup_idx'),
        ),
    ]
